version: '3.8'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 3000:3000
    environment:
      - PG_PASSWORD=password
      - PG_DB=entrega5
      - PG_USER=postgres
      - PG_HOST=db
      - SECRET=qualquerCoisa
    volumes:
      - .:/code 

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=entrega5
    ports:
      - 5432:5432
